# TODO:
#   high prio:
#   - better categorize the exported variables and aliases
#   - apply program settings only when it is appropriate
#     - general configs only if the program is present on the system
#     - graphical configs only when it is appropriate
#       - general configs only if any graphical server is present
#       - wayland configs only if wayland is present
#   low prio:
#   - apply certain color configs only if a program is of supportedversion

# fix all sudo aliases
alias sudo='sudo '

# TODO: do I need to export them?
HISTSIZE=5000
SAVEHIST=100000

# enable vim bindings; extremely useful, despite many consider it useless :/
bindkey -v

# nethack: {{{
# TODO: integrate with dotfiles
export NETHACKOPTIONS="@$(xdg-user-dir)/.config/nethack/nethackrc"
# }}}

# colored output: {{{
export CLICOLOR=1
alias ip='ip --color=auto'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export BEMENU_OPTS="-ci -l 16 -W 0.3 -p 'exec:' -P '>' -w --scrollbar always \
--scf '#f84b8c' --hf '#f84b8c' --tf '#f84b8c'"
# }}}

# `pass` configs: {{{
export PASSWORD_STORE_DIR=$HOME/.local/share/password-store
export PASSWORD_STORE_CLIP_TIME=5
export PASSWORD_STORE_GENERATED_LENGTH=1000
# }}}

export PATH=$HOME/.local/bin:$PATH

export EDITOR=/usr/bin/nvim
export TERMINAL_EMULATOR=/usr/bin/foot
export WWW_HOME=https://lite.duckduckgo.com/lite
export GNUPGHOME=$HOME/.local/share/gnupg

export XDG_CURRENT_DESKTOP=sway
export QT_QPA_PLATFORM="wayland;xcb"

# nmcli: {{{
alias n='nmcli'
alias na='n connection show --active'
# }}}

alias e=$EDITOR
alias si='swayimg'
alias wlp='wl-paste'
alias wlc='wl-copy'
alias bli="bluetoothctl"

alias df='df -h'
alias ls='exa --group --classify --group-directories-first --git'
alias l='ls -lh'
alias la='l -a'
alias dnd='dragon-drop -x'
alias auracle='auracle --sort=votes'
